stages:
- name: docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: torans/test
      registry: 127.0.0.1:34369
- name: deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#集群消息'
    notifier: c-dgnrz:n-lp888
  condition:
  - Success
  - Changed
  - Failed
