stages:
- name: docker
  steps:
  - runScriptConfig:
      image: nginx
      shellScript: |-
        #!/bin/bash -ilex
        echo "ok!"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: 冉俊
    notifier: c-dgnrz:n-wzpfw
  condition:
  - Success
  - Changed
  - Failed
