stages:
- name: docker
  steps:
  - runScriptConfig:
      image: nginx
      shellScript: |-
        #!/bin/bash
        /usr/bin/supervisord
timeout: 60
notification:
  recipients:
  - recipient: 冉俊
    notifier: c-dgnrz:n-wzpfw
  condition:
  - Success
  - Changed
  - Failed
